"""empty message

Revision ID: 48a8e90022d4
Revises: fd79503179dd
Create Date: 2025-05-11 13:21:40.701549

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a8e90022d4'
down_revision = 'fd79503179dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_alias_suffix', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_alias_suffix')
    # ### end Alembic commands ###
