name: SimpleLogin actions

on:
  push:
    branches:
      - build
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/build' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lhbdhr/simplelogin-app-cli-arm64-build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # We need to checkout the repository in order for the "Create Sentry release" to work
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare version file
        run: |
          scripts/generate-build-info.sh ${{ github.sha }} ${{ github.ref_name }}
          cat app/build_info.py

      - name: Build image and publish to Docker Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
